name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_TARGET_PLATFORM: linux/arm/v7

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      with:
        context: nginx-proxy
        run: docker build . --file ./Dockerfile --tag my-image-name:$(date +%s)
